# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://www.txjt.netlify.com'
baseurl: ''
title: 'TXJT team | Principles of Digital Fabrication'
description: 'SmartPot'
permalink: pretty
logo: "https://media.licdn.com/dms/image/C560BAQE1DB1jA3rb8Q/company-logo_400_400/0?e=1559779200&v=beta&t=YT-1D1Nr71AD0ZTXVOxASrEULP2eyCvPVygUCoUtbzU"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  Introductory report: /report/
  Blog: /blog/
  Bill of Materials: /BOM/
  Repo: "https://github.com/txjt/SmartPot"

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://wallpapercave.com/wp/wp1913752.jpg"
