# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://www.txjt.netlify.com'
baseurl: ''
title: 'TXJT team | Principles of Digital Fabrication'
description: 'SmartPot'
permalink: pretty
logo: "https://upload.wikimedia.org/wikipedia/en/a/a6/University_of_Oulu_logo.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  Introductory report: /report/
  Summary report: /sum_report/
  Blog: /blog/
  Bill of Materials: /BOM/
  Repo: "https://github.com/txjt/SmartPot"

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Here you can find the preview of our blog posts. Please clik the header to read all of each post"
    feature_text: |
      Welcome to my blog
    feature_image: "https://wallpapercave.com/wp/wp1913752.jpg"
